name: Trigger Webhook on Push or Merge

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - closed  # Includes merged PRs

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook on push or merged PR
        run: |
          curl -X POST https://2184cc71-68b6-41a9-a0d9-86695b3bc292-00-32rk7rmb9nuuc.picard.replit.dev/webhook \
               -H "Content-Type: application/json" \
               -d '{
                     "event": "${{ github.event_name }}",
                     "action": "${{ github.event.action }}",
                     "merged": "${{ github.event.pull_request.merged || false }}",
                     "repository": "${{ github.repository }}",
                     "sender": "${{ github.actor }}"
                   }'
