name: Trigger Webhook on Push

on:
  push:
    branches:
      - main

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to Replit webhook
        run: |
          curl -X POST https://2184cc71-68b6-41a9-a0d9-86695b3bc292-00-32rk7rmb9nuuc.picard.replit.dev/webhook \
               -H "Content-Type: application/json" \
               -d '{"event":"push","repository":"${{ github.repository }}"}'
